# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test_Cases_Ind.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re,os
from Write_Data import WriteDate
import ipaddress 
dir_path =  os.path.dirname(os.path.abspath(__file__))
print(dir_path)

# A regular expression, to extract the % complete.
progress_re = re.compile("Total complete: (\d+)%")

def simple_percent_parser(output):
    """
    Matches lines using the progress_re regex,
    returning a single integer for the % progress.
    """
    m = progress_re.search(output)
    if m:
        pc_complete = m.group(1)
        return int(pc_complete)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(841, 636)
        # self.setWindowFlag()
        self.Main_widget = QtWidgets.QWidget(MainWindow)
        self.Main_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.Main_widget.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    background:transparent;\n"
"    padding:0;\n"
"    margin:o;\n"
"    color:#fff;\n"
"}\n"
"#Main_widget{\n"
"background-color: #1f232a;\n"
"}\n"
"#leftmenusub_container{\n"
"background-color: #16191d;\n"
"}\n"
"#leftmenusub_container, QPushButton{\n"
"    text-align:left;\n"
"    padding:5px,10px;\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"#centerMenuSubConatiner{\n"
"background-color: #2c313c;\n"
"}\n"
"#MoreMenuFrame{\n"
"background-color: #16191d;\n"
"border-radius:10px;\n"
"}\n"
"#headerContainer{\n"
"    background-color: #2c313c;\n"
"}\n"
"\n"
"")
        self.Main_widget.setObjectName("Main_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        # self.left_menu_container = QtWidgets.QWidget(self.Main_widget)
        # self.left_menu_container.setObjectName("left_menu_container")
        # self.verticalLayout = QtWidgets.QVBoxLayout(self.left_menu_container)
        # self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout.setSpacing(0)
        # self.verticalLayout.setObjectName("verticalLayout")
        # self.leftmenusub_container = QtWidgets.QWidget(self.left_menu_container)
        # self.leftmenusub_container.setObjectName("leftmenusub_container")
        # self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftmenusub_container)
        # self.verticalLayout_2.setContentsMargins(10, 0, 5, 0)
        # self.verticalLayout_2.setSpacing(0)
        # self.verticalLayout_2.setObjectName("verticalLayout_2")
        # self.frame = QtWidgets.QFrame(self.leftmenusub_container)
        # self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame.setObjectName("frame")
        # self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        # self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout_2.setSpacing(0)
        # self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.menuBtn = QtWidgets.QPushButton(self.frame)
        # self.menuBtn.setText("")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/icons/icons/align-justify.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.menuBtn.setIcon(icon)
        # self.menuBtn.setIconSize(QtCore.QSize(24, 24))
        # self.menuBtn.setObjectName("menuBtn")
        # self.horizontalLayout_2.addWidget(self.menuBtn)
        # self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        # self.frame_2 = QtWidgets.QFrame(self.leftmenusub_container)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        # self.frame_2.setSizePolicy(sizePolicy)
        # self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_2.setObjectName("frame_2")
        # self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        # self.verticalLayout_3.setContentsMargins(0, 10, 0, 10)
        # self.verticalLayout_3.setSpacing(0)
        # self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.homeBtn = QtWidgets.QPushButton(self.frame_2)
        # icon1 = QtGui.QIcon()
        # icon1.addPixmap(QtGui.QPixmap(":/icons/icons/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.homeBtn.setIcon(icon1)
        # self.homeBtn.setIconSize(QtCore.QSize(24, 24))
        # self.homeBtn.setObjectName("homeBtn")
        # self.verticalLayout_3.addWidget(self.homeBtn)
        # self.reportBtn = QtWidgets.QPushButton(self.frame_2)
        # icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/icons/icons/printer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.reportBtn.setIcon(icon2)
        # self.reportBtn.setIconSize(QtCore.QSize(24, 24))
        # self.reportBtn.setObjectName("reportBtn")
        # self.verticalLayout_3.addWidget(self.reportBtn)
        # self.verticalLayout_2.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        # spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.verticalLayout_2.addItem(spacerItem)
        # self.frame_3 = QtWidgets.QFrame(self.leftmenusub_container)
        # self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_3.setObjectName("frame_3")
        # self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        # self.verticalLayout_5.setContentsMargins(0, 10, 0, 10)
        # self.verticalLayout_5.setSpacing(0)
        # self.verticalLayout_5.setObjectName("verticalLayout_5")
        # self.infoBtn = QtWidgets.QPushButton(self.frame_3)
        # icon3 = QtGui.QIcon()
        # icon3.addPixmap(QtGui.QPixmap(":/icons/icons/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.infoBtn.setIcon(icon3)
        # self.infoBtn.setIconSize(QtCore.QSize(24, 24))
        # self.infoBtn.setObjectName("infoBtn")
        # self.verticalLayout_5.addWidget(self.infoBtn)
        # self.helpBtn = QtWidgets.QPushButton(self.frame_3)
        # icon4 = QtGui.QIcon()
        # icon4.addPixmap(QtGui.QPixmap(":/icons/icons/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.helpBtn.setIcon(icon4)
        # self.helpBtn.setIconSize(QtCore.QSize(24, 24))
        # self.helpBtn.setObjectName("helpBtn")
        # self.verticalLayout_5.addWidget(self.helpBtn)
        # self.verticalLayout_2.addWidget(self.frame_3)
        # self.verticalLayout.addWidget(self.leftmenusub_container, 0, QtCore.Qt.AlignLeft)
        # self.horizontalLayout.addWidget(self.left_menu_container, 0, QtCore.Qt.AlignLeft)
        self.main_body_container = QtWidgets.QWidget(self.Main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_container.sizePolicy().hasHeightForWidth())
        self.main_body_container.setSizePolicy(sizePolicy)
        self.main_body_container.setStyleSheet("")
        self.main_body_container.setObjectName("main_body_container")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.main_body_container)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.headerContainer = QtWidgets.QWidget(self.main_body_container)
        self.headerContainer.setObjectName("headerContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.headerContainer)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.swNameFrame = QtWidgets.QFrame(self.headerContainer)
        self.swNameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.swNameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.swNameFrame.setObjectName("swNameFrame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.swNameFrame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.imageLable = QtWidgets.QLabel(self.swNameFrame)
        self.imageLable.setMaximumSize(QtCore.QSize(60, 40))
        self.imageLable.setText("")
        self.imageLable.setPixmap(QtGui.QPixmap(":/images/vvdn_logo.png"))
        self.imageLable.setScaledContents(True)
        self.imageLable.setObjectName("imageLable")
        self.horizontalLayout_6.addWidget(self.imageLable)
        self.swNameLable = QtWidgets.QLabel(self.swNameFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.swNameLable.setFont(font)
        self.swNameLable.setObjectName("swNameLable")
        self.horizontalLayout_6.addWidget(self.swNameLable)
        self.horizontalLayout_4.addWidget(self.swNameFrame)
        self.crossbarFrame = QtWidgets.QFrame(self.headerContainer)
        self.crossbarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.crossbarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.crossbarFrame.setObjectName("crossbarFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.crossbarFrame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.minBtn = QtWidgets.QPushButton(self.crossbarFrame)
        self.minBtn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/minus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minBtn.setIcon(icon5)
        self.minBtn.setIconSize(QtCore.QSize(24, 24))
        self.minBtn.setObjectName("minBtn")
        self.horizontalLayout_5.addWidget(self.minBtn)
        self.maxBtn = QtWidgets.QPushButton(self.crossbarFrame)
        self.maxBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maxBtn.setIcon(icon6)
        self.maxBtn.setIconSize(QtCore.QSize(24, 24))
        self.maxBtn.setObjectName("maxBtn")
        self.horizontalLayout_5.addWidget(self.maxBtn)
        self.exitBtn = QtWidgets.QPushButton(self.crossbarFrame)
        self.exitBtn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/x.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon7)
        self.exitBtn.setIconSize(QtCore.QSize(24, 24))
        self.exitBtn.setObjectName("exitBtn")
        self.horizontalLayout_5.addWidget(self.exitBtn)
        self.horizontalLayout_4.addWidget(self.crossbarFrame, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.headerContainer, 0, QtCore.Qt.AlignTop)
        self.mainbodyContainer = QtWidgets.QWidget(self.main_body_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainbodyContainer.sizePolicy().hasHeightForWidth())
        self.mainbodyContainer.setSizePolicy(sizePolicy)
        self.mainbodyContainer.setObjectName("mainbodyContainer")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.mainbodyContainer)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.testCaseFrame = QtWidgets.QFrame(self.mainbodyContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testCaseFrame.sizePolicy().hasHeightForWidth())
        self.testCaseFrame.setSizePolicy(sizePolicy)
        self.testCaseFrame.setMinimumSize(QtCore.QSize(700, 400))
        self.testCaseFrame.setMaximumSize(QtCore.QSize(1000, 400))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.testCaseFrame.setFont(font)
        self.testCaseFrame.setStyleSheet("#testCaseFrame{\n"
"background-color: #16191d;\n"
"}\n"
"#testSelFrame, #UserInputFrame{\n"
"background-color: #1f232a;\n"
"}\n"
"\n"
"QCheckBox{\n"
"    background-color: rgb(43, 43, 43);\n"
"    border-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    padding:3px 10px;\n"
"    border-radius:10px\n"
"}")
        self.testCaseFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testCaseFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.testCaseFrame.setObjectName("testCaseFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.testCaseFrame)
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout_12.setSpacing(7)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.testSelFrame = QtWidgets.QFrame(self.testCaseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testSelFrame.sizePolicy().hasHeightForWidth())
        self.testSelFrame.setSizePolicy(sizePolicy)
        self.testSelFrame.setStyleSheet("")
        self.testSelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.testSelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.testSelFrame.setObjectName("testSelFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.testSelFrame)
        self.gridLayout_2.setContentsMargins(-1, 5, -1, 6)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.testSelFrame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton_2.setStyleSheet("background-color: rgb(102, 0, 0);")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon8)
        self.pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.pushButton = QtWidgets.QPushButton(self.testSelFrame)
        self.pushButton.setMinimumSize(QtCore.QSize(40, 30))
        self.pushButton.setStyleSheet("background-color: rgb(0, 47, 0);")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/play.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setIconSize(QtCore.QSize(18, 18))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1, QtCore.Qt.AlignRight)


        #######################################################################################################################################################
        ####################### Add combobox ################
        self.comboBox = QtWidgets.QComboBox(self.testSelFrame)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.comboBox.setStyleSheet("background-color: #16191d;")


        ########################################################################
        ## Add test case python files name 
        ########################################################################
        geek_list = ['M_STC_ID_001','M_STC_ID_002','M_STC_ID_003','M_STC_ID_004','M_STC_ID_005','M_STC_ID_006']
        self.comboBox.addItems(geek_list)
        self.gridLayout_2.addWidget(self.comboBox, 2, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.testSelFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.verticalLayout_12.addWidget(self.testSelFrame, 0, QtCore.Qt.AlignTop)


        #######################################################################################################################################################
        #################### Scroll Area ######################
        self.UserInputFrame = QtWidgets.QFrame(self.testCaseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHeightForWidth(self.UserInputFrame.sizePolicy().hasHeightForWidth())
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.UserInputFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.UserInputArea = QtWidgets.QScrollArea(self.UserInputFrame)
        self.UserInputArea.setWidgetResizable(True)
        self.UIscrollWidgetCont = QtWidgets.QWidget()
        self.UIscrollWidgetCont.setGeometry(QtCore.QRect(0, 0, 664, 239))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.UIscrollWidgetCont)
        self.verticalLayout_6.setObjectName("verticalLayout_6")

        #######################################################################################################################################################
        #################### Make Input Frame for taking inputs ######################
        self.tc01Frame = QtWidgets.QFrame(self.UIscrollWidgetCont)
        self.tc01Frame.setStyleSheet("*{\n"
            "    border:none;\n"
            "    background-color: transparent;\n"
            "    background:transparent;\n"
            "    padding:0;\n"
            "    margin:o;\n"
            "    color:#fff;\n"
            "}\n"
            "#UserInputWidget{\n"
            "background-color: #1f232a;\n"
            "}\n"
            "QLineEdit{\n"
            "    background-color: rgb(19, 39, 59);\n"
            "    height:20px;\n"
            "    max-height:20px;\n"
            "    border-radius:8px;\n"
            "    border-bottom:2px solid rgba(105,118,132,255);\n"
            "}\n"
            "QPushButton{\n"
            "    background-color: #4b6043;\n"
            "    height:20px;\n"
            "    min-width:150px;\n"
            "    max-height:20px;\n"
            "    text-align:center;\n"
            "    border-radius:8px;\n"
            "    border-bottom:2px solid rgba(105,118,132,255);\n"
            "}")  
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tc01Frame)
        self.make_qlineedits = {'super_user':'RU UserName..','super_user_pswrd':'RU Password..','paragon_ip':'Paragon Neo IP..',
        'paragon_port':'PTP & SYNCE Port{Eg. 1/2}..','du_pswrd':'DU Password..',
        r'remote_path':'Software File Path {eg. sftp://vvdn@192.168.4.15:22/home/user/filename.zip}..',
        'corrupt_file_path':'Software Corrupt file{eg. sftp://vvdn@192.168.4.15:22/home/user/corrupt.zip}..',
        'syslog_path':'System Log Path{eg. /media/sd-mmcblk0p4/garuda.log}..',
        'tx_arfcn':'TX ARFCN{eg. 633333}..','rx_arfcn':'RX ARFCN{eg. 633333}..','channel_bandwidth':'Bandwidth{Eg. 100/40/10}..',
        'center_channel_bandwidth':'Center Frequency{eg. 3.26}..'}
        self.dict_of_input = {}
        i = 0
        for key,val in self.make_qlineedits.items():
            self.Qlineedit = QtWidgets.QLineEdit(self.tc01Frame)
            self.Qlineedit.setPlaceholderText(val)
            self.Qlineedit.setAlignment(QtCore.Qt.AlignCenter)
            self.gridLayout_3.addWidget(self.Qlineedit, i, 0, 1, 1)
            self.dict_of_input[key] = self.Qlineedit
            i+=1

        #######################################################################################################################################################
        #################### Make submit button ######################
        self.SubmitBtn = QtWidgets.QPushButton(self.tc01Frame)
        self.SubmitBtn.setStyleSheet("background-color: rgb(188, 188, 188);")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/check-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SubmitBtn.setIcon(icon10)
        self.SubmitBtn.setIconSize(QtCore.QSize(18, 18))
        self.gridLayout_3.addWidget(self.SubmitBtn, i, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.tc01Frame)
        self.UserInputArea.setWidget(self.UIscrollWidgetCont)
        self.verticalLayout_4.addWidget(self.UserInputArea)
        self.verticalLayout_12.addWidget(self.UserInputFrame)
        self.verticalLayout_10.addWidget(self.testCaseFrame, 0, QtCore.Qt.AlignHCenter)
        ###########################################################################################################################################



        ########################################################################
        ## Initialize Result COntainer
        ########################################################################
        self.testCaseResultsContainer = QtWidgets.QWidget(self.mainbodyContainer)
        self.testCaseResultsContainer.setStyleSheet("#testCaseResultsContainer{\n"
"background-color: rgb(61, 61, 61);\n"
"}\n"
"\n"
"\n"
"#outFrame,#outLable{\n"
"background-color: #16191d;\n"
"}")
        self.testCaseResultsContainer.setObjectName("testCaseResultsContainer")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.testCaseResultsContainer)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.outLable = QtWidgets.QLabel(self.testCaseResultsContainer)
        self.outLable.setMinimumSize(QtCore.QSize(0, 15))
        self.outLable.setMaximumSize(QtCore.QSize(16777215, 15))
        self.outLable.setAlignment(QtCore.Qt.AlignCenter)
        self.outLable.setObjectName("outLable")
        self.verticalLayout_14.addWidget(self.outLable)
        self.outFrame = QtWidgets.QFrame(self.testCaseResultsContainer)
        self.outFrame.setMinimumSize(QtCore.QSize(0, 100))
        self.outFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outFrame.setObjectName("outFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.outFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.outText = QtWidgets.QPlainTextEdit(self.outFrame)
        self.outText.setObjectName("outText")
        self.gridLayout.addWidget(self.outText, 1, 0, 1, 1)
        self.verticalLayout_14.addWidget(self.outFrame)
        self.verticalLayout_10.addWidget(self.testCaseResultsContainer)
        self.verticalLayout_9.addWidget(self.mainbodyContainer)
        self.mainbodyContainer.raise_()
        self.headerContainer.raise_()
        self.horizontalLayout.addWidget(self.main_body_container)
        self.side_menu_num = 0

        self.SubmitBtn.clicked.connect(self.Check_User_Input)
        self.pushButton.pressed.connect(self.start_process)
        MainWindow.setCentralWidget(self.Main_widget)


        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def message(self, s):
        self.outText.appendPlainText(s)

    def add_test(self):
        test_case_list = ['M_STC_ID_001','M_STC_ID_002','M_STC_ID_003','M_STC_ID_004']
        pass

    
    def validate_ip(self,ip_str):  
        try:  
            ip_obj = ipaddress.ip_address(ip_str)  
            print(f"The IP address {ip_obj} is valid")
            return True  
        except ValueError:  
            print(f"The IP address {ip_str} is not valid")
            return False

    def Check_User_Input(self):
        msg = QtWidgets.QMessageBox()
        values = list(self.dict_of_input.values())
        new_dict = {}
        if values[2] == True and (values[3] == 1 or values[3] == 2):
            msg.setText('Please Enter a valid value of {0}/{1}'.format(values[2],values[3]))
            msg.exec_()
        for key,val in self.dict_of_input.items():
            print(val.text())
            if val.text() == '':
                    msg.setText('Please Enter a valid value of {}'.format(key))
                    msg.exec_()
                    break
            new_dict[key] = val.text()
        else:
            msg.setText('Success')
            msg.exec_()
        filename = '{}/M_Plane/M_Plane_Conf_04/M_Plane_Sanity/input.ini'.format(dir_path)
        # print(self.dict_of_input.values())
        WriteDate(new_dict,filename)
        # print(new_dict)
        

    def start_process(self):
            content = self.comboBox.currentText()
            self.outText.clear()
            self.message("Executing process")
            self.p = QtCore.QProcess()  # Keep a reference to the QProcess (e.g. on self) while it's running.
            self.outText.appendPlainText('+'*100)
            self.p.start("/home/vvdn/Pictures/PyQT5/M_Plane_GUI/web_gui/bin/python", ['{}/M_Plane/M_Plane_Conf_04/M_Plane_Sanity/{}.py'.format(dir_path,content)])
            # self.p.start("python3", ['test.py'.format(content)])
            self.p.readyReadStandardOutput.connect(self.handle_stdout)
            self.p.readyReadStandardError.connect(self.handle_stderr)
            self.p.stateChanged.connect(self.handle_state)
            self.p.finished.connect(self.process_finished)  # Clean up once complete.
            
        # pass
    def handle_stderr(self):
        data = self.p.readAllStandardError()
        stderr = bytes(data).decode("utf8")
        # progress = simple_percent_parser(stderr)
        # if progress:
        #     self.progress.setValue(progress)
        self.message(stderr)

    def handle_stdout(self):
        data = self.p.readAllStandardOutput()
        stdout = bytes(data).decode("utf8")
        self.message(stdout)

    def handle_state(self, state):
        states = {
            QtCore.QProcess.NotRunning: 'Not running',
            QtCore.QProcess.Starting: 'Starting',
            QtCore.QProcess.Running: 'Running',
        }
        print(state,'state')
        state_name = states[state]
        self.message(f"State changed: {state_name}")

    def process_finished(self):
        self.message("Process finished.")
        self.p = None

    def side_menu_state(self):
        if self.side_menu_num == 0:
            self.animation1 = QtCore.QPropertyAnimation(self.leftmenusub_container, b"minimumWidth")
            self.animation1.setDuration(500)
            self.animation1.setStartValue(40)
            self.animation1.setEndValue(123)
            self.animation1.setEasingCurve(QtCore.QEasingCurve.InOutQuart)
            self.animation1.start()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.menuBtn.setToolTip(_translate("MainWindow", "Menu"))
        # self.homeBtn.setToolTip(_translate("MainWindow", "Home"))
        # self.homeBtn.setText(_translate("MainWindow", "Home"))
        # self.reportBtn.setToolTip(_translate("MainWindow", "View Reports"))
        # self.reportBtn.setText(_translate("MainWindow", "Reports"))
        # self.infoBtn.setToolTip(_translate("MainWindow", "Information"))
        # self.infoBtn.setText(_translate("MainWindow", "Information"))
        # self.helpBtn.setToolTip(_translate("MainWindow", "Get more help"))
        # self.helpBtn.setText(_translate("MainWindow", "Help"))
        self.swNameLable.setText(_translate("MainWindow", "O-RAN Conformance Automation Test Suit "))
        self.pushButton_2.setText(_translate("MainWindow", "Stop"))
        self.pushButton.setText(_translate("MainWindow", "Execute"))
        # self.comboBox.setItemText(0, _translate("MainWindow", "M_CTC_ID_001"))
        # self.comboBox.setItemText(1, _translate("MainWindow", "M_CTC_ID_002"))
        # self.comboBox.setItemText(2, _translate("MainWindow", "M_CTC_ID_003"))
        self.label.setText(_translate("MainWindow", "Management Plane Conformance Test Case"))
        self.SubmitBtn.setText(_translate("MainWindow", "Submit"))
        self.outLable.setText(_translate("MainWindow", "OUTPUT"))
        # self.stopBtn.setText(_translate("MainWindow", "Stop"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
